# Generated by Django 5.0.2 on 2024-07-18 08:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailUserAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email_login', models.EmailField(max_length=254, unique=True)),
                ('email_password', models.CharField(max_length=128, verbose_name='email password')),
                ('first_name', models.CharField(blank=True, max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'EmailUserAccount',
                'verbose_name_plural': 'EmailUserAccounts',
            },
        ),
        migrations.CreateModel(
            name='EmailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='Subject')),
                ('sent_at', models.DateTimeField(verbose_name='Sent Date')),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Received Date')),
                ('body', models.TextField(verbose_name='Body')),
                ('to_email', models.CharField(max_length=256, verbose_name='Email to')),
                ('from_email', models.CharField(max_length=256, verbose_name='Email from')),
                ('attachments', models.JSONField(default=list, verbose_name='Attachments in json')),
                ('email_service', models.CharField(choices=[('imap.yandex.ru', 'Yandex'), ('imap.gmail.com', 'Gmail'), ('imap.mail.ru', 'Mail.ru')], max_length=50, verbose_name='Email Service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
